"""Initial migration

Revision ID: 6999ed80402e
Revises: 8b14ccb80274
Create Date: 2025-01-18 22:23:28.535415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6999ed80402e'
down_revision = '8b14ccb80274'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    # ### end Alembic commands ###
